application:  hudapp2-158221
version: 1
runtime: python27 # needed to set up the correct runtime environment
api_version: 1
threadsafe: true # needed for python27
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: index.app
libraries:
- name: jinja2
  version: latest
- name: ssl
  version: 2.7.11

